package consts

const (
	SaasUrl               = "https://cloud.khulnasoft.com"
	SaasEu1Url            = "https://eu-1.cloud.khulnasoft.com"
	SaasAsia1Url          = "https://asia-1.cloud.khulnasoft.com"
	SaasAsia2Url          = "https://asia-2.cloud.khulnasoft.com"
	SaaSAu2Url            = "https://ap-2.cloud.khulnasoft.com"
	SaasDevUrl            = "https://cloud-dev.khulnasoft.com"
	SaasDevTokenUrl       = "https://stage.api.cloudsploit.com"
	SaasDevProvUrl        = "https://prov-dev.cloud.khulnasoft.com"
	SaasTokenUrl          = "https://api.cloudsploit.com"
	SaasEu1TokenUrl       = "https://eu-1.api.cloudsploit.com"
	SaasAsia1TokenUrl     = "https://asia-1.api.cloudsploit.com"
	SaasAsia2TokenUrl     = "https://asia-2.api.cloudsploit.com"
	SaasAu2TokenUrl       = "https://ap-2.api.cloudsploit.com"
	SaasProvUrl           = "https://prov.cloud.khulnasoft.com"
	SaasEu1ProvUrl        = "https://prov-eu-1.cloud.khulnasoft.com"
	SaasAsia1ProvUrl      = "https://prov-asia-1.cloud.khulnasoft.com"
	SaasAsia2ProvUrl      = "https://prov-asia-2.cloud.khulnasoft.com"
	SaasAu2ProvUrl        = "https://prov-ap-2.cloud.khulnasoft.com"
	SamlSettingsApiPath   = "/api/v1/settings/SAMLSettings/SAMLSettings"
	OIDCSettingsApiPath   = "/api/v1/settings/OIDCSettings/OIDCSettings"
	OpenIdSettingsApiPath = "/api/v1/settings/OIDCSettings/OpenIdSettings"
	LdapSettingsApiPath   = "/api/v1/settings/ldap"
)
